# Generated by Django 5.0.4 on 2024-05-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inventoryorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='order',
            name='agent',
        ),
        migrations.AddField(
            model_name='product',
            name='available_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_lists', models.IntegerField(blank=True, null=True)),
                ('possible_defect', models.IntegerField(blank=True, null=True)),
                ('price_per_list', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryOrder',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
