# Generated by Django 5.0.4 on 2024-05-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paper_papertype_remove_product_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
