# Generated by Django 5.0.4 on 2024-05-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_products_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
