# Generated by Django 5.0.4 on 2024-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_serviceorder_quantity_order_num_of_lists_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sqr_meter",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
