# Generated by Django 5.0.4 on 2024-05-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_sqr_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sqr_meter',
            new_name='total_sqr_meter',
        ),
    ]
