# Generated by Django 5.0.4 on 2024-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_orderpics_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="num_of_product_per_list",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
