# Generated by Django 5.0.4 on 2024-05-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customerdebt_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.order'),
        ),
    ]
