# Generated by Django 5.0.4 on 2024-05-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_orderpayment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_list',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_sqr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
    ]
