# Generated by Django 5.0.4 on 2024-05-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_customerdebt_amount_alter_debt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lists_per_paper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
