# Generated by Django 5.0.4 on 2024-05-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_paymentmethod_orderpayment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdebt",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debt",
                to="main.customer",
            ),
        ),
    ]
