# Generated by Django 4.2.13 on 2024-05-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_customerdebt_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
        migrations.CreateModel(
            name='InventoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_expenses', to='main.order')),
            ],
        ),
    ]
