# Generated by Django 4.2.13 on 2024-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_inventoryexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_service_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
