# Generated by Django 4.2.13 on 2024-11-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_expenses', to='main.order')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paper')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_expenses', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.expensecategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
