# Generated by Django 4.2.13 on 2024-11-20 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperexpenses',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
