# Generated by Django 4.2.13 on 2024-05-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_inventoryexpense'),
        ('accounting', '0002_debt_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_expenses', to='main.order')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paper')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_expenses', to='main.order')),
            ],
        ),
    ]
