# Generated by Django 4.2.13 on 2024-05-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_inventoryexpense'),
        ('accounting', '0003_paperexpenses_inventoryexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexpense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
        migrations.AddField(
            model_name='paperexpenses',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
