# Generated by Django 4.2.13 on 2024-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_inventoryexpense_branch_paperexpenses_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
