# Generated by Django 4.2.13 on 2024-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
