# Generated by Django 4.2.13 on 2024-11-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_expenses_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['id']},
        ),
    ]
